### ISSUE TITLE
Default Composer directory in Windows.

### ISSUE THREAD

**Issue by alystair** [faelv/composer-companion#3]
When Composer is installed in Windows, it is added to %PATH% by default - most likely in  `C:\ProgramData\ComposerSetup\bin`.

Should make this default place to check, and fallback to locating 'composer' within %PATH%...

**Comment by alystair** [comment]
actually for further compat should use `%PROGRAMDATA%\\ComposerSetup\\bin\\composer.bat`

**Comment by faelv** [comment]
When using the installer, just like you said, the install location (```%PROGRAMDATA%\ComposerSetup\bin``` for all users or ```%USERPROFILE%\AppData\Roaming\Composer\vendor\bin``` for current user only) is added to _PATH_, so why look into a specific location (or locations) if it's already in the _PATH_? Even if installed manually it will most likely be added to _PATH_. For other scenarios there's a setting: ```composerCompanion.executablePath```.

I will leave it open though, in case someone else thinks it's a good ideia.

**Comment by alystair** [comment]
Well, only reason was that as soon as I installed the extension, it told me to add executablePath myself, would have thought it would check those and not require me to input it manually.

**Comment by faelv** [comment]
Now that you mentioned about the warning, you're right, simple executing ```composer```, fails in Windows **even** if it's in the PATH. Not great for the user experience.

**Comment by alystair** [comment]
Unsure why that happens, considering if I open a cmd prompt or terminal it works just fine. Guess it's a VS code extension specific issue?

**Comment by faelv** [comment]
> Unsure why that happens, considering if I open a cmd prompt or terminal it works just fine. Guess it's a VS code extension specific issue?

My thoughts exactly

**Comment by faelv** [comment]
Closed by d02a7ceb891a47803665fcf2fdcf6e18263077e4
