### ISSUE TITLE
Crippled package names

### ISSUE THREAD

**Issue by chaosben** [faelv/composer-companion#9]
If i try to require 'algo26-matthias/idna-convert' via commandline the package-name gets crippled.
![image](https://user-images.githubusercontent.com/1180488/107202530-95bf1300-69fa-11eb-85b4-eac5750afe73.png)
![image](https://user-images.githubusercontent.com/1180488/107202555-9eafe480-69fa-11eb-8852-513c225be913.png)

**Comment by faelv** [comment]
Thanks for letting me know, it's fixed in [v0.2.5](https://github.com/faelv/composer-companion/releases/tag/v0.2.5)

**Comment by chaosben** [comment]
👍 Great response-time. Thank you!
